apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tt7vonatg-nodejs
  janus-idp.io/tekton: tt7vonatg-nodejs
  backstage.io/kubernetes-id: tt7vonatg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tt7vonatg-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
